import 'package:flutter/material.dart';

// مولّد آليًّا: محتوى دليل الاستخدام (البنية + 13 لغة).
class HgItem {
  final IconData icon; final String title; final String desc;
  const HgItem(this.icon, this.title, this.desc);
}
class HgSection {
  final IconData icon; final Color color; final bool expanded;
  final String title; final List<HgItem> items;
  const HgSection(this.icon, this.color, this.expanded, this.title, this.items);
}
class HgChrome { final String subtitle; final String items; final String updated;
  const HgChrome(this.subtitle, this.items, this.updated); }

const _c1 = Color(0xFF5C6BC0);
const _c2 = Color(0xFF26A69A);
const _c3 = Color(0xFFEF6C00);
const _c4 = Color(0xFF42A5F5);
const _c6 = Color(0xFFE53935);
const _c8 = Color(0xFF6D4C41);
const _c5 = Color(0xFF7E57C2); // قسم التنبيهات والمنبّه
const _c7 = Color(0xFFEC407A); // قسم التحسينات الحديثة

const Map<String, List<HgSection>> _hg = {
  'en': [
    HgSection(Icons.add_circle, _c1, true, 'Create a note (+)', [
      HgItem(Icons.edit_note, 'Note', 'Plain text, direction per line'),
      HgItem(Icons.checklist, 'Checklist', 'Lines with checkboxes'),
      HgItem(Icons.mic, 'Voice note', 'Record audio'),
      HgItem(Icons.image, 'Image', 'Attach a photo'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Formatting', [
      HgItem(Icons.format_bold, 'Bold · Italic · Underline', 'On the selected text'),
      HgItem(Icons.format_color_text, 'Colors', 'Text and highlight color'),
      HgItem(Icons.title, 'Headings & lists', 'Titles, bullets, numbers'),
      HgItem(Icons.format_align_right, 'Alignment', 'Right / center / left'),
      HgItem(Icons.format_line_spacing, 'Line spacing', 'Selected lines (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Voice typing', 'Speak and it writes'),
      HgItem(Icons.picture_as_pdf, 'Export PDF', 'Save the note as PDF'),
      HgItem(Icons.description, 'Export Word', 'Save a .doc file'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Editor tools', [
      HgItem(Icons.push_pin, 'Pin', 'Pin the note to top'),
      HgItem(Icons.palette_outlined, 'Color & page', 'Background, style, ruling'),
      HgItem(Icons.star, 'Favorite', 'Mark as favorite'),
      HgItem(Icons.alarm, 'Reminder', 'One-time or repeating'),
      HgItem(Icons.label_outline, 'Tags', 'Add tags to the note'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Home & navigation', [
      HgItem(Icons.search, 'Search', 'Find in your notes'),
      HgItem(Icons.tune, 'Advanced search', 'Filter by type/date'),
      HgItem(Icons.calendar_month, 'Calendar', 'Notes by date'),
      HgItem(Icons.label, 'Categories', 'Filter by category'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Security & sync', [
      HgItem(Icons.lock, 'Lock note', 'Protect with a PIN'),
      HgItem(Icons.visibility_off, 'Privacy mode', 'Hide card contents'),
      HgItem(Icons.backup_outlined, 'Backup', 'Save and restore'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Encrypted cloud sync'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Reminders & alarm', [
      HgItem(Icons.notifications_active, 'Reminder types', 'General, medication, appointment, occasion'),
      HgItem(Icons.timer, 'Alert before by', '5 min / 15 min / hour / day'),
      HgItem(Icons.place, 'Appointment location', 'Google Maps link or pick'),
      HgItem(Icons.attach_file, 'Invitation', 'Attach an image or PDF'),
      HgItem(Icons.library_music, 'Sound library', 'Tones + your device tones'),
      HgItem(Icons.alarm_on, 'Reliable alarm', 'Works when closed/rebooted, full-screen, raises volume'),
      HgItem(Icons.history, 'Notification center log', 'Every fired reminder — logged automatically, with delete'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Recent improvements', [
      HgItem(Icons.brush, 'Advanced drawing', 'Per-stroke color & width, brush, eraser'),
      HgItem(Icons.tune, 'Default reminder settings', 'Tone, snooze, volume, pre-alert'),
      HgItem(Icons.lock, 'Encrypted & safe', 'On-device encrypted data + auto backup'),
      HgItem(Icons.cloud_done, 'Secure sync', 'Authenticated & resilient (never deletes data)'),
      HgItem(Icons.system_update, 'In-app update', 'Check & install new versions from Settings — no manual download'),
      HgItem(Icons.restart_alt, 'Expired reminders', 'Past one-time reminders fade out — reactivate to reschedule'),
      HgItem(Icons.medication, 'Medication courses', 'Set total doses; remaining counts down by time; past & upcoming doses'),
      HgItem(Icons.checklist_rtl, 'Multi-select', 'Long-press → Select: archive/delete/move/pin in bulk'),
      HgItem(Icons.bar_chart, 'Note statistics', 'Words, characters, lines & reading time'),
      HgItem(Icons.label_important_outline, 'Category counts', 'Chips show how many notes in each'),
      HgItem(Icons.alarm, 'Reminder badge', 'Cards show an alarm icon when a reminder is set'),
      HgItem(Icons.density_small, 'Compact view', 'Smaller cards to show more notes — in Settings'),
      HgItem(Icons.verified_outlined, 'Verified backups', 'Integrity checked as soon as they are made'),
      HgItem(Icons.restore_page_outlined, 'Safe restore', 'Auto safety snapshot + one-tap undo restore'),
      HgItem(Icons.swipe, 'Swipe actions', 'Swipe right to archive, left to delete (list view)'),
      HgItem(Icons.search, 'Search highlight', 'Matches highlighted on cards • friendly dates'),
      HgItem(Icons.sell_outlined, 'Tags on cards', 'Colored tag chips show on each note'),
      HgItem(Icons.image_outlined, 'Share as image', 'Share any note as a styled image'),
      HgItem(Icons.data_object, 'JSON export/import', 'Portable readable backup of your notes'),
      HgItem(Icons.repeat, 'Custom repeat', 'Repeat any reminder every N days'),
      HgItem(Icons.fact_check_outlined, 'Checklist progress', 'Progress bar shows done/total tasks'),
      HgItem(Icons.label_outline, 'Colored tags', 'Pick a color per tag (long-press) on the Tags page'),
      HgItem(Icons.dashboard_outlined, 'Streamlined navigation', 'Header: quick actions • ⋮: quick services • ☰: settings & management'),
      HgItem(Icons.palette_outlined, 'System colors', 'Theme from your wallpaper (Android 12+) — in Settings'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'More', [
      HgItem(Icons.format_textdirection_r_to_l, 'Per-line direction', 'Arabic right, English left'),
      HgItem(Icons.archive_outlined, 'Archive & Trash', 'Restore your notes'),
      HgItem(Icons.settings_outlined, 'Settings', 'Default page & language'),
    ]),
  ],
  'ar': [
    HgSection(Icons.add_circle, _c1, true, 'إنشاء ملاحظة (+)', [
      HgItem(Icons.edit_note, 'ملاحظة', 'نص عادي، اتجاه لكل سطر'),
      HgItem(Icons.checklist, 'قائمة مهام', 'أسطر بمربعات اختيار'),
      HgItem(Icons.mic, 'ملاحظة صوتية', 'تسجيل صوت'),
      HgItem(Icons.image, 'صورة', 'إرفاق صورة'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'التنسيق', [
      HgItem(Icons.format_bold, 'غامق · مائل · تسطير', 'على النص المحدَّد'),
      HgItem(Icons.format_color_text, 'الألوان', 'لون النص والخلفية'),
      HgItem(Icons.title, 'العناوين والقوائم', 'عناوين، نقاط، أرقام'),
      HgItem(Icons.format_align_right, 'المحاذاة', 'يمين / وسط / يسار'),
      HgItem(Icons.format_line_spacing, 'تباعد الأسطر', 'للأسطر المحدَّدة (1.0–2.0)'),
      HgItem(Icons.mic_none, 'إملاء صوتي', 'تحدّث فيُكتب'),
      HgItem(Icons.picture_as_pdf, 'تصدير PDF', 'حفظ الملاحظة PDF'),
      HgItem(Icons.description, 'تصدير Word', 'حفظ ملف .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'أدوات المحرّر', [
      HgItem(Icons.push_pin, 'تثبيت', 'تثبيت الملاحظة أعلى'),
      HgItem(Icons.palette_outlined, 'اللون والصفحة', 'خلفية، نمط، تسطير'),
      HgItem(Icons.star, 'مفضّلة', 'تمييز كمفضّلة'),
      HgItem(Icons.alarm, 'تذكير', 'مرّة أو متكرّر'),
      HgItem(Icons.label_outline, 'وسوم', 'إضافة وسوم'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'الرئيسية والتنقّل', [
      HgItem(Icons.search, 'بحث', 'ابحث في ملاحظاتك'),
      HgItem(Icons.tune, 'بحث متقدّم', 'تصفية بالنوع/التاريخ'),
      HgItem(Icons.calendar_month, 'التقويم', 'ملاحظات حسب التاريخ'),
      HgItem(Icons.label, 'التصنيفات', 'تصفية حسب التصنيف'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'الأمان والمزامنة', [
      HgItem(Icons.lock, 'قفل الملاحظة', 'حماية برقم سرّي'),
      HgItem(Icons.visibility_off, 'وضع الخصوصية', 'إخفاء محتوى البطاقات'),
      HgItem(Icons.backup_outlined, 'نسخ احتياطي', 'حفظ واستعادة'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'مزامنة سحابية مشفّرة'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'التنبيهات والمنبّه', [
      HgItem(Icons.notifications_active, 'أنواع التنبيه', 'عام، دواء، موعد، مناسبة'),
      HgItem(Icons.timer, 'تنبيه قبل الوقت', '5د / 15د / ساعة / يوم'),
      HgItem(Icons.place, 'موقع الموعد', 'رابط خرائط جوجل أو اختيار'),
      HgItem(Icons.attach_file, 'الدعوة', 'إرفاق صورة أو PDF'),
      HgItem(Icons.library_music, 'مكتبة الأصوات', 'نغمات + نغمات جهازك'),
      HgItem(Icons.alarm_on, 'منبّه موثوق', 'يعمل والتطبيق مغلق/بعد التشغيل، شاشة كاملة، يرفع الصوت'),
      HgItem(Icons.history, 'سجلّ مركز التنبيهات', 'كل تنبيه يفوت وقته يُسجَّل تلقائيًّا في تبويب «السجل» — مع حذف'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'تحسينات حديثة', [
      HgItem(Icons.brush, 'الرسم المتقدّم', 'لون وسماكة لكل خط + فرشاة وممحاة'),
      HgItem(Icons.tune, 'إعدادات التنبيه الافتراضية', 'نغمة، غفوة، رفع الصوت، قبل الوقت'),
      HgItem(Icons.lock, 'تخزين مشفّر آمن', 'بياناتك محليّة مشفّرة + نسخ تلقائي'),
      HgItem(Icons.cloud_done, 'مزامنة مؤمّنة', 'مشفّرة ومتينة (لا تحذف بياناتك)'),
      HgItem(Icons.system_update, 'تحديث داخل التطبيق', 'تحقّق وثبّت النسخ الجديدة من الإعدادات — بلا تحميل يدويّ'),
      HgItem(Icons.restart_alt, 'تنبيهات منتهية', 'تنبيهات المرّة الواحدة الفائتة تبهت — أعِد تنشيطها لجدولة جديدة'),
      HgItem(Icons.medication, 'كورسات الدواء', 'حدّد عدد الجرعات؛ المتبقّي ينقص زمنيًّا؛ جرعات سابقة ولاحقة'),
      HgItem(Icons.checklist_rtl, 'تحديد متعدّد', 'ضغطة مطوّلة ← تحديد: أرشفة/حذف/نقل/تثبيت دفعة'),
      HgItem(Icons.bar_chart, 'إحصائيات الملاحظة', 'كلمات وأحرف وأسطر وزمن قراءة'),
      HgItem(Icons.label_important_outline, 'عدّاد التصنيفات', 'تعرض الشرائح عدد ملاحظات كل تصنيف'),
      HgItem(Icons.alarm, 'مؤشّر التنبيه', 'تعرض البطاقة أيقونة منبّه عند وجود تنبيه'),
      HgItem(Icons.density_small, 'عرض مدمج', 'بطاقات أصغر لعرض عدد أكبر — من الإعدادات'),
      HgItem(Icons.verified_outlined, 'نسخ متحقَّقة', 'يُتحقَّق من سلامتها لحظة إنشائها'),
      HgItem(Icons.restore_page_outlined, 'استعادة آمنة', 'لقطة أمان تلقائية + تراجع عن الاستعادة بضغطة'),
      HgItem(Icons.swipe, 'سحب البطاقة', 'اسحب يمينًا للأرشفة ويسارًا للحذف (وضع القائمة)'),
      HgItem(Icons.search, 'تمييز البحث', 'تُظلَّل الكلمة المطابقة • تواريخ ودّية (اليوم/أمس)'),
      HgItem(Icons.sell_outlined, 'وسوم على البطاقات', 'شرائح وسوم ملوّنة تظهر على كل ملاحظة'),
      HgItem(Icons.image_outlined, 'مشاركة كصورة', 'شارك أي ملاحظة كصورة أنيقة'),
      HgItem(Icons.data_object, 'تصدير/استيراد JSON', 'نسخة نصّية مقروءة وقابلة للنقل لملاحظاتك'),
      HgItem(Icons.repeat, 'تكرار مخصّص', 'كرّر أي تنبيه كل N يوم'),
      HgItem(Icons.fact_check_outlined, 'تقدّم قائمة المهام', 'شريط يعرض المنجَز من الإجمالي'),
      HgItem(Icons.label_outline, 'وسوم ملوّنة', 'اختر لونًا لكل وسم بضغطة مطوّلة في صفحة الوسوم'),
      HgItem(Icons.dashboard_outlined, 'تنظيم الواجهة', 'الهيدر إجراءات سريعة • ⋮ خدمات سريعة • ☰ الإعدادات والإدارة'),
      HgItem(Icons.palette_outlined, 'ألوان النظام', 'سمة مشتقّة من خلفية جهازك (أندرويد 12+) — من الإعدادات'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'المزيد', [
      HgItem(Icons.format_textdirection_r_to_l, 'اتجاه لكل سطر', 'العربي يمين والإنجليزي يسار'),
      HgItem(Icons.archive_outlined, 'الأرشيف والمهملات', 'استرجاع ملاحظاتك'),
      HgItem(Icons.settings_outlined, 'الإعدادات', 'الصفحة الافتراضية واللغة'),
    ]),
  ],
  'es': [
    HgSection(Icons.add_circle, _c1, true, 'Crear una nota (+)', [
      HgItem(Icons.edit_note, 'Nota', 'Texto simple, dirección por línea'),
      HgItem(Icons.checklist, 'Lista de tareas', 'Líneas con casillas'),
      HgItem(Icons.mic, 'Nota de voz', 'Grabar audio'),
      HgItem(Icons.image, 'Imagen', 'Adjuntar una foto'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Formato', [
      HgItem(Icons.format_bold, 'Negrita · Cursiva · Subrayado', 'En el texto seleccionado'),
      HgItem(Icons.format_color_text, 'Colores', 'Color de texto y fondo'),
      HgItem(Icons.title, 'Títulos y listas', 'Títulos, viñetas, números'),
      HgItem(Icons.format_align_right, 'Alineación', 'Derecha / centro / izquierda'),
      HgItem(Icons.format_line_spacing, 'Interlineado', 'Líneas seleccionadas (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Dictado por voz', 'Habla y se escribe'),
      HgItem(Icons.picture_as_pdf, 'Exportar PDF', 'Guardar la nota como PDF'),
      HgItem(Icons.description, 'Exportar Word', 'Guardar un archivo .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Herramientas del editor', [
      HgItem(Icons.push_pin, 'Fijar', 'Fijar la nota arriba'),
      HgItem(Icons.palette_outlined, 'Color y página', 'Fondo, estilo, líneas'),
      HgItem(Icons.star, 'Favorito', 'Marcar como favorito'),
      HgItem(Icons.alarm, 'Recordatorio', 'Único o repetido'),
      HgItem(Icons.label_outline, 'Etiquetas', 'Añadir etiquetas'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Inicio y navegación', [
      HgItem(Icons.search, 'Buscar', 'Buscar en tus notas'),
      HgItem(Icons.tune, 'Búsqueda avanzada', 'Filtrar por tipo/fecha'),
      HgItem(Icons.calendar_month, 'Calendario', 'Notas por fecha'),
      HgItem(Icons.label, 'Categorías', 'Filtrar por categoría'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Seguridad y sincronización', [
      HgItem(Icons.lock, 'Bloquear nota', 'Proteger con PIN'),
      HgItem(Icons.visibility_off, 'Modo privado', 'Ocultar contenido'),
      HgItem(Icons.backup_outlined, 'Copia de seguridad', 'Guardar y restaurar'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Sincronización cifrada'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Recordatorios y alarma', [
      HgItem(Icons.notifications_active, 'Tipos de recordatorio', 'General, medicación, cita, evento'),
      HgItem(Icons.timer, 'Avisar antes', '5 min / 15 min / hora / día'),
      HgItem(Icons.place, 'Ubicación de la cita', 'Enlace de Google Maps o elegir'),
      HgItem(Icons.attach_file, 'Invitación', 'Adjuntar imagen o PDF'),
      HgItem(Icons.library_music, 'Biblioteca de sonidos', 'Tonos + tonos del dispositivo'),
      HgItem(Icons.alarm_on, 'Alarma fiable', 'Funciona cerrada/reiniciada, pantalla completa, sube volumen'),
      HgItem(Icons.history, 'Registro del centro de notificaciones', 'Cada recordatorio disparado se registra solo — con borrado'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Mejoras recientes', [
      HgItem(Icons.brush, 'Dibujo avanzado', 'Color y grosor por trazo, pincel, goma'),
      HgItem(Icons.tune, 'Ajustes de recordatorio', 'Tono, posponer, volumen, pre-aviso'),
      HgItem(Icons.lock, 'Cifrado y seguro', 'Datos cifrados en el dispositivo + copia automática'),
      HgItem(Icons.cloud_done, 'Sync segura', 'Autenticada y resistente (nunca borra datos)'),
      HgItem(Icons.system_update, 'Actualización integrada', 'Busca e instala nuevas versiones desde Ajustes'),
      HgItem(Icons.restart_alt, 'Recordatorios expirados', 'Los de una vez pasados se atenúan — reactiva para reprogramar'),
      HgItem(Icons.medication, 'Tratamientos', 'Define dosis totales; lo restante baja con el tiempo; dosis pasadas y próximas'),
      HgItem(Icons.checklist_rtl, 'Selección múltiple', 'Mantén pulsado → Seleccionar: acciones en lote'),
      HgItem(Icons.bar_chart, 'Estadísticas de nota', 'Palabras, caracteres, líneas y tiempo de lectura'),
      HgItem(Icons.label_important_outline, 'Recuento por categoría', 'Los chips muestran cuántas notas hay'),
      HgItem(Icons.alarm, 'Indicador de recordatorio', 'Las tarjetas muestran un icono de alarma'),
      HgItem(Icons.density_small, 'Vista compacta', 'Tarjetas más pequeñas — en Ajustes'),
      HgItem(Icons.verified_outlined, 'Copias verificadas', 'Integridad comprobada al crearlas'),
      HgItem(Icons.restore_page_outlined, 'Restauración segura', 'Copia de seguridad automática + deshacer restauración'),
      HgItem(Icons.swipe, 'Deslizar', 'Derecha para archivar, izquierda para borrar (lista)'),
      HgItem(Icons.search, 'Resaltado de búsqueda', 'Coincidencias resaltadas • fechas amigables'),
      HgItem(Icons.sell_outlined, 'Etiquetas en tarjetas', 'Chips de etiqueta de colores en cada nota'),
      HgItem(Icons.image_outlined, 'Compartir como imagen', 'Comparte una nota como imagen con estilo'),
      HgItem(Icons.data_object, 'Exportar/importar JSON', 'Copia legible y portátil de tus notas'),
      HgItem(Icons.repeat, 'Repetición personalizada', 'Repite cualquier recordatorio cada N días'),
      HgItem(Icons.fact_check_outlined, 'Progreso de checklist', 'Barra que muestra hechas/total'),
      HgItem(Icons.label_outline, 'Etiquetas de colores', 'Elige un color por etiqueta (pulsación larga) en Etiquetas'),
      HgItem(Icons.dashboard_outlined, 'Navegación organizada', 'Cabecera: acciones rápidas • ⋮: servicios rápidos • ☰: ajustes y gestión'),
      HgItem(Icons.palette_outlined, 'Colores del sistema', 'Tema desde tu fondo (Android 12+) — en Ajustes'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Más', [
      HgItem(Icons.format_textdirection_r_to_l, 'Dirección por línea', 'Árabe a la derecha, inglés a la izquierda'),
      HgItem(Icons.archive_outlined, 'Archivo y papelera', 'Restaurar tus notas'),
      HgItem(Icons.settings_outlined, 'Ajustes', 'Página e idioma por defecto'),
    ]),
  ],
  'de': [
    HgSection(Icons.add_circle, _c1, true, 'Notiz erstellen (+)', [
      HgItem(Icons.edit_note, 'Notiz', 'Einfacher Text, Richtung pro Zeile'),
      HgItem(Icons.checklist, 'Checkliste', 'Zeilen mit Kästchen'),
      HgItem(Icons.mic, 'Sprachnotiz', 'Audio aufnehmen'),
      HgItem(Icons.image, 'Bild', 'Foto anhängen'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Formatierung', [
      HgItem(Icons.format_bold, 'Fett · Kursiv · Unterstrichen', 'Auf dem markierten Text'),
      HgItem(Icons.format_color_text, 'Farben', 'Text- und Hintergrundfarbe'),
      HgItem(Icons.title, 'Überschriften & Listen', 'Titel, Aufzählung, Nummern'),
      HgItem(Icons.format_align_right, 'Ausrichtung', 'Rechts / Mitte / links'),
      HgItem(Icons.format_line_spacing, 'Zeilenabstand', 'Markierte Zeilen (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Spracheingabe', 'Sprich, es schreibt'),
      HgItem(Icons.picture_as_pdf, 'PDF exportieren', 'Notiz als PDF speichern'),
      HgItem(Icons.description, 'Word exportieren', '.doc-Datei speichern'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Editor-Werkzeuge', [
      HgItem(Icons.push_pin, 'Anheften', 'Notiz oben anheften'),
      HgItem(Icons.palette_outlined, 'Farbe & Seite', 'Hintergrund, Stil, Linien'),
      HgItem(Icons.star, 'Favorit', 'Als Favorit markieren'),
      HgItem(Icons.alarm, 'Erinnerung', 'Einmalig oder wiederholt'),
      HgItem(Icons.label_outline, 'Tags', 'Tags hinzufügen'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Start & Navigation', [
      HgItem(Icons.search, 'Suche', 'In Notizen suchen'),
      HgItem(Icons.tune, 'Erweiterte Suche', 'Nach Typ/Datum filtern'),
      HgItem(Icons.calendar_month, 'Kalender', 'Notizen nach Datum'),
      HgItem(Icons.label, 'Kategorien', 'Nach Kategorie filtern'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Sicherheit & Sync', [
      HgItem(Icons.lock, 'Notiz sperren', 'Mit PIN schützen'),
      HgItem(Icons.visibility_off, 'Privatmodus', 'Inhalte verbergen'),
      HgItem(Icons.backup_outlined, 'Sicherung', 'Speichern & wiederherstellen'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Verschlüsselte Sync'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Erinnerungen & Wecker', [
      HgItem(Icons.notifications_active, 'Erinnerungstypen', 'Allgemein, Medikament, Termin, Anlass'),
      HgItem(Icons.timer, 'Vorher erinnern', '5 Min / 15 Min / Stunde / Tag'),
      HgItem(Icons.place, 'Terminort', 'Google-Maps-Link oder wählen'),
      HgItem(Icons.attach_file, 'Einladung', 'Bild oder PDF anhängen'),
      HgItem(Icons.library_music, 'Klangbibliothek', 'Töne + Gerätetöne'),
      HgItem(Icons.alarm_on, 'Zuverlässiger Wecker', 'Auch geschlossen/nach Neustart, Vollbild, lauter'),
      HgItem(Icons.history, 'Protokoll der Mitteilungszentrale', 'Jede ausgelöste Erinnerung wird automatisch protokolliert — löschbar'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Neue Verbesserungen', [
      HgItem(Icons.brush, 'Erweitertes Zeichnen', 'Farbe & Stärke pro Strich, Pinsel, Radierer'),
      HgItem(Icons.tune, 'Standard-Erinnerung', 'Ton, Schlummern, Lautstärke, Vorab-Hinweis'),
      HgItem(Icons.lock, 'Verschlüsselt & sicher', 'Daten verschlüsselt auf dem Gerät + Auto-Backup'),
      HgItem(Icons.cloud_done, 'Sichere Sync', 'Authentifiziert & robust (löscht nie Daten)'),
      HgItem(Icons.system_update, 'In-App-Update', 'Neue Versionen aus den Einstellungen prüfen & installieren'),
      HgItem(Icons.restart_alt, 'Abgelaufene Erinnerungen', 'Vergangene Einmal-Erinnerungen verblassen — Reaktivieren zum Neuplanen'),
      HgItem(Icons.medication, 'Medikamenten-Kuren', 'Gesamtdosen festlegen; Rest zählt zeitlich herunter; vergangene & kommende Dosen'),
      HgItem(Icons.checklist_rtl, 'Mehrfachauswahl', 'Lang drücken → Auswählen: Sammelaktionen'),
      HgItem(Icons.bar_chart, 'Notiz-Statistik', 'Wörter, Zeichen, Zeilen & Lesezeit'),
      HgItem(Icons.label_important_outline, 'Kategorie-Zähler', 'Chips zeigen die Anzahl der Notizen'),
      HgItem(Icons.alarm, 'Erinnerungs-Symbol', 'Karten zeigen ein Wecker-Symbol bei Erinnerung'),
      HgItem(Icons.density_small, 'Kompakte Ansicht', 'Kleinere Karten — in Einstellungen'),
      HgItem(Icons.verified_outlined, 'Geprüfte Sicherungen', 'Integrität sofort beim Erstellen geprüft'),
      HgItem(Icons.restore_page_outlined, 'Sicheres Wiederherstellen', 'Auto-Sicherung + Wiederherstellung rückgängig'),
      HgItem(Icons.swipe, 'Wischgesten', 'Rechts archivieren, links löschen (Listenansicht)'),
      HgItem(Icons.search, 'Suchhervorhebung', 'Treffer markiert • freundliche Daten'),
      HgItem(Icons.sell_outlined, 'Tags auf Karten', 'Farbige Tag-Chips auf jeder Notiz'),
      HgItem(Icons.image_outlined, 'Als Bild teilen', 'Notiz als gestaltetes Bild teilen'),
      HgItem(Icons.data_object, 'JSON Export/Import', 'Lesbares, portables Backup deiner Notizen'),
      HgItem(Icons.repeat, 'Eigene Wiederholung', 'Jede Erinnerung alle N Tage wiederholen'),
      HgItem(Icons.fact_check_outlined, 'Checklisten-Fortschritt', 'Balken zeigt erledigt/gesamt'),
      HgItem(Icons.label_outline, 'Farbige Tags', 'Farbe je Tag wählen (lang drücken) auf der Tags-Seite'),
      HgItem(Icons.dashboard_outlined, 'Aufgeräumte Navigation', 'Kopf: Schnellaktionen • ⋮: Schnellzugriff • ☰: Einstellungen & Verwaltung'),
      HgItem(Icons.palette_outlined, 'Systemfarben', 'Theme vom Hintergrundbild (Android 12+) — in Einstellungen'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Mehr', [
      HgItem(Icons.format_textdirection_r_to_l, 'Richtung pro Zeile', 'Arabisch rechts, Englisch links'),
      HgItem(Icons.archive_outlined, 'Archiv & Papierkorb', 'Notizen wiederherstellen'),
      HgItem(Icons.settings_outlined, 'Einstellungen', 'Standardseite & Sprache'),
    ]),
  ],
  'fil': [
    HgSection(Icons.add_circle, _c1, true, 'Gumawa ng tala (+)', [
      HgItem(Icons.edit_note, 'Tala', 'Plain text, direksyon kada linya'),
      HgItem(Icons.checklist, 'Checklist', 'Mga linyang may checkbox'),
      HgItem(Icons.mic, 'Talang boses', 'Mag-record ng audio'),
      HgItem(Icons.image, 'Larawan', 'Maglakip ng larawan'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Pag-format', [
      HgItem(Icons.format_bold, 'Bold · Italic · Underline', 'Sa napiling teksto'),
      HgItem(Icons.format_color_text, 'Mga kulay', 'Kulay ng teksto at highlight'),
      HgItem(Icons.title, 'Heading at listahan', 'Pamagat, bullet, numero'),
      HgItem(Icons.format_align_right, 'Pagkakahanay', 'Kanan / gitna / kaliwa'),
      HgItem(Icons.format_line_spacing, 'Espasyo ng linya', 'Mga napiling linya (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Pagdidikta sa boses', 'Magsalita, isusulat'),
      HgItem(Icons.picture_as_pdf, 'I-export sa PDF', 'I-save bilang PDF'),
      HgItem(Icons.description, 'I-export sa Word', 'I-save na .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Mga tool sa editor', [
      HgItem(Icons.push_pin, 'I-pin', 'I-pin sa itaas'),
      HgItem(Icons.palette_outlined, 'Kulay at pahina', 'Background, istilo, linya'),
      HgItem(Icons.star, 'Paborito', 'Markahan paborito'),
      HgItem(Icons.alarm, 'Paalala', 'Isahan o paulit-ulit'),
      HgItem(Icons.label_outline, 'Mga tag', 'Magdagdag ng tag'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Home at nabigasyon', [
      HgItem(Icons.search, 'Hanapin', 'Maghanap sa tala'),
      HgItem(Icons.tune, 'Advanced na paghahanap', 'Filter ayon sa uri/petsa'),
      HgItem(Icons.calendar_month, 'Kalendaryo', 'Tala ayon sa petsa'),
      HgItem(Icons.label, 'Kategorya', 'Filter ayon sa kategorya'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Seguridad at sync', [
      HgItem(Icons.lock, 'I-lock ang tala', 'Protektahan ng PIN'),
      HgItem(Icons.visibility_off, 'Privacy mode', 'Itago ang nilalaman'),
      HgItem(Icons.backup_outlined, 'Backup', 'I-save at ibalik'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Naka-encrypt na sync'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Mga paalala at alarm', [
      HgItem(Icons.notifications_active, 'Uri ng paalala', 'Pangkalahatan, gamot, appointment, okasyon'),
      HgItem(Icons.timer, 'Paalala bago ang oras', '5 min / 15 min / oras / araw'),
      HgItem(Icons.place, 'Lokasyon ng appointment', 'Google Maps link o pumili'),
      HgItem(Icons.attach_file, 'Imbitasyon', 'Maglakip ng larawan o PDF'),
      HgItem(Icons.library_music, 'Aklatan ng tunog', 'Mga tono + tono ng device'),
      HgItem(Icons.alarm_on, 'Maaasahang alarm', 'Gumagana kahit sarado/na-restart, full-screen, nilalakasan'),
      HgItem(Icons.history, 'Log ng notification center', 'Bawat na-trigger na paalala, awtomatikong naitatala — may delete'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Mga bagong pagpapabuti', [
      HgItem(Icons.brush, 'Advanced na pagguhit', 'Kulay at kapal kada guhit, brush, pambura'),
      HgItem(Icons.tune, 'Default na paalala', 'Tono, snooze, volume, pre-alert'),
      HgItem(Icons.lock, 'Naka-encrypt at ligtas', 'Naka-encrypt sa device + auto backup'),
      HgItem(Icons.cloud_done, 'Ligtas na sync', 'May pagpapatunay at matatag (di nagbubura)'),
      HgItem(Icons.system_update, 'In-app update', 'Tingnan at i-install ang bagong bersyon sa Settings'),
      HgItem(Icons.restart_alt, 'Tapos na paalala', 'Kumukupas ang lumipas — i-reactivate para i-reschedule'),
      HgItem(Icons.medication, 'Kurso ng gamot', 'Itakda ang kabuuang dosis; bumababa ayon sa oras; nakaraan at paparating'),
      HgItem(Icons.checklist_rtl, 'Multi-select', 'Pindutin nang matagal → Pumili: bulk actions'),
      HgItem(Icons.bar_chart, 'Estadistika ng note', 'Salita, karakter, linya at oras ng pagbasa'),
      HgItem(Icons.label_important_outline, 'Bilang ng kategorya', 'Ipinapakita ng chip ang dami ng note'),
      HgItem(Icons.alarm, 'Badge ng paalala', 'May alarm icon ang card kapag may paalala'),
      HgItem(Icons.density_small, 'Compact view', 'Mas maliit na card — sa Settings'),
      HgItem(Icons.verified_outlined, 'Verified na backup', 'Sinusuri agad ang integridad'),
      HgItem(Icons.restore_page_outlined, 'Ligtas na restore', 'Auto safety snapshot + undo restore'),
      HgItem(Icons.swipe, 'Swipe', 'Pakanan i-archive, pakaliwa burahin (list view)'),
      HgItem(Icons.search, 'Highlight ng paghahanap', 'Naka-highlight ang tugma • madaling petsa'),
      HgItem(Icons.sell_outlined, 'Tag sa cards', 'Makukulay na tag chip sa bawat note'),
      HgItem(Icons.image_outlined, 'Ibahagi bilang larawan', 'Ibahagi ang note bilang magandang larawan'),
      HgItem(Icons.data_object, 'JSON export/import', 'Nababasa, portable na backup ng mga note'),
      HgItem(Icons.repeat, 'Custom na pag-ulit', 'Ulitin ang paalala kada N araw'),
      HgItem(Icons.fact_check_outlined, 'Progreso ng checklist', 'Bar na nagpapakita ng tapos/kabuuan'),
      HgItem(Icons.label_outline, 'May kulay na tag', 'Pumili ng kulay kada tag (pindutin nang matagal)'),
      HgItem(Icons.dashboard_outlined, 'Maayos na navigation', 'Header: mabilis na aksyon • ⋮: mabilis na serbisyo • ☰: setting at pamamahala'),
      HgItem(Icons.palette_outlined, 'Mga kulay ng system', 'Tema mula sa wallpaper (Android 12+) — sa Settings'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Iba pa', [
      HgItem(Icons.format_textdirection_r_to_l, 'Direksyon kada linya', 'Arabe kanan, Ingles kaliwa'),
      HgItem(Icons.archive_outlined, 'Archive at basurahan', 'Ibalik ang tala'),
      HgItem(Icons.settings_outlined, 'Mga Setting', 'Default na pahina at wika'),
    ]),
  ],
  'fr': [
    HgSection(Icons.add_circle, _c1, true, 'Créer une note (+)', [
      HgItem(Icons.edit_note, 'Note', 'Texte simple, direction par ligne'),
      HgItem(Icons.checklist, 'Liste de tâches', 'Lignes avec cases'),
      HgItem(Icons.mic, 'Note vocale', 'Enregistrer l’audio'),
      HgItem(Icons.image, 'Image', 'Joindre une photo'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Mise en forme', [
      HgItem(Icons.format_bold, 'Gras · Italique · Souligné', 'Sur le texte sélectionné'),
      HgItem(Icons.format_color_text, 'Couleurs', 'Couleur du texte et du fond'),
      HgItem(Icons.title, 'Titres et listes', 'Titres, puces, numéros'),
      HgItem(Icons.format_align_right, 'Alignement', 'Droite / centre / gauche'),
      HgItem(Icons.format_line_spacing, 'Interligne', 'Lignes sélectionnées (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Dictée vocale', 'Parlez, ça s’écrit'),
      HgItem(Icons.picture_as_pdf, 'Exporter en PDF', 'Enregistrer en PDF'),
      HgItem(Icons.description, 'Exporter en Word', 'Enregistrer un .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Outils de l’éditeur', [
      HgItem(Icons.push_pin, 'Épingler', 'Épingler en haut'),
      HgItem(Icons.palette_outlined, 'Couleur et page', 'Fond, style, lignes'),
      HgItem(Icons.star, 'Favori', 'Marquer comme favori'),
      HgItem(Icons.alarm, 'Rappel', 'Unique ou répété'),
      HgItem(Icons.label_outline, 'Étiquettes', 'Ajouter des étiquettes'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Accueil et navigation', [
      HgItem(Icons.search, 'Rechercher', 'Chercher dans vos notes'),
      HgItem(Icons.tune, 'Recherche avancée', 'Filtrer par type/date'),
      HgItem(Icons.calendar_month, 'Calendrier', 'Notes par date'),
      HgItem(Icons.label, 'Catégories', 'Filtrer par catégorie'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Sécurité et sync', [
      HgItem(Icons.lock, 'Verrouiller la note', 'Protéger par PIN'),
      HgItem(Icons.visibility_off, 'Mode privé', 'Masquer le contenu'),
      HgItem(Icons.backup_outlined, 'Sauvegarde', 'Enregistrer et restaurer'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Sync chiffrée'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Rappels et alarme', [
      HgItem(Icons.notifications_active, 'Types de rappel', 'Général, médicament, rendez-vous, occasion'),
      HgItem(Icons.timer, 'Alerter avant', '5 min / 15 min / heure / jour'),
      HgItem(Icons.place, 'Lieu du rendez-vous', 'Lien Google Maps ou choisir'),
      HgItem(Icons.attach_file, 'Invitation', 'Joindre une image ou un PDF'),
      HgItem(Icons.library_music, 'Bibliothèque de sons', 'Sonneries + sons de l’appareil'),
      HgItem(Icons.alarm_on, 'Alarme fiable', 'Marche fermée/redémarrée, plein écran, monte le volume'),
      HgItem(Icons.history, 'Journal du centre de notifications', 'Chaque rappel déclenché est enregistré — avec suppression'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Améliorations récentes', [
      HgItem(Icons.brush, 'Dessin avancé', 'Couleur et épaisseur par trait, pinceau, gomme'),
      HgItem(Icons.tune, 'Réglages de rappel', 'Sonnerie, rappel, volume, pré-alerte'),
      HgItem(Icons.lock, 'Chiffré et sûr', 'Données chiffrées sur l’appareil + sauvegarde auto'),
      HgItem(Icons.cloud_done, 'Sync sécurisée', 'Authentifiée et robuste (ne supprime jamais)'),
      HgItem(Icons.system_update, 'Mise à jour intégrée', 'Vérifier et installer les nouvelles versions depuis Réglages'),
      HgItem(Icons.restart_alt, 'Rappels expirés', 'Les rappels uniques passés s’estompent — réactiver pour reprogrammer'),
      HgItem(Icons.medication, 'Cures de médicaments', 'Définir le total ; le reste décompte avec le temps ; doses passées et à venir'),
      HgItem(Icons.checklist_rtl, 'Sélection multiple', 'Appui long → Sélectionner : actions groupées'),
      HgItem(Icons.bar_chart, 'Statistiques de note', 'Mots, caractères, lignes et temps de lecture'),
      HgItem(Icons.label_important_outline, 'Compteurs de catégories', 'Les puces affichent le nombre de notes'),
      HgItem(Icons.alarm, 'Badge de rappel', 'Une icône d’alarme apparaît sur la carte'),
      HgItem(Icons.density_small, 'Vue compacte', 'Cartes plus petites — dans Réglages'),
      HgItem(Icons.verified_outlined, 'Sauvegardes vérifiées', 'Intégrité contrôlée dès la création'),
      HgItem(Icons.restore_page_outlined, 'Restauration sûre', 'Instantané auto + annuler la restauration'),
      HgItem(Icons.swipe, 'Balayage', 'À droite pour archiver, à gauche pour supprimer (liste)'),
      HgItem(Icons.search, 'Surlignage recherche', 'Correspondances surlignées • dates conviviales'),
      HgItem(Icons.sell_outlined, 'Tags sur les cartes', 'Puces de tags colorées sur chaque note'),
      HgItem(Icons.image_outlined, 'Partager en image', 'Partagez une note en image stylée'),
      HgItem(Icons.data_object, 'Export/import JSON', 'Sauvegarde lisible et portable de vos notes'),
      HgItem(Icons.repeat, 'Répétition personnalisée', 'Répéter un rappel tous les N jours'),
      HgItem(Icons.fact_check_outlined, 'Progression de checklist', 'Barre : tâches faites/total'),
      HgItem(Icons.label_outline, 'Tags colorés', 'Choisir une couleur par tag (appui long) sur la page Tags'),
      HgItem(Icons.dashboard_outlined, 'Navigation organisée', 'En-tête : actions rapides • ⋮ : services rapides • ☰ : réglages et gestion'),
      HgItem(Icons.palette_outlined, 'Couleurs du système', 'Thème depuis le fond d’écran (Android 12+) — dans Réglages'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Plus', [
      HgItem(Icons.format_textdirection_r_to_l, 'Direction par ligne', 'Arabe à droite, anglais à gauche'),
      HgItem(Icons.archive_outlined, 'Archives et corbeille', 'Restaurer vos notes'),
      HgItem(Icons.settings_outlined, 'Paramètres', 'Page et langue par défaut'),
    ]),
  ],
  'id': [
    HgSection(Icons.add_circle, _c1, true, 'Buat catatan (+)', [
      HgItem(Icons.edit_note, 'Catatan', 'Teks biasa, arah per baris'),
      HgItem(Icons.checklist, 'Daftar tugas', 'Baris dengan kotak centang'),
      HgItem(Icons.mic, 'Catatan suara', 'Rekam audio'),
      HgItem(Icons.image, 'Gambar', 'Lampirkan foto'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Pemformatan', [
      HgItem(Icons.format_bold, 'Tebal · Miring · Garis bawah', 'Pada teks terpilih'),
      HgItem(Icons.format_color_text, 'Warna', 'Warna teks dan sorotan'),
      HgItem(Icons.title, 'Judul & daftar', 'Judul, poin, angka'),
      HgItem(Icons.format_align_right, 'Perataan', 'Kanan / tengah / kiri'),
      HgItem(Icons.format_line_spacing, 'Spasi baris', 'Baris terpilih (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Pengetikan suara', 'Bicara, ditulis'),
      HgItem(Icons.picture_as_pdf, 'Ekspor PDF', 'Simpan sebagai PDF'),
      HgItem(Icons.description, 'Ekspor Word', 'Simpan berkas .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Alat editor', [
      HgItem(Icons.push_pin, 'Sematkan', 'Sematkan ke atas'),
      HgItem(Icons.palette_outlined, 'Warna & halaman', 'Latar, gaya, garis'),
      HgItem(Icons.star, 'Favorit', 'Tandai favorit'),
      HgItem(Icons.alarm, 'Pengingat', 'Sekali atau berulang'),
      HgItem(Icons.label_outline, 'Tag', 'Tambah tag'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Beranda & navigasi', [
      HgItem(Icons.search, 'Cari', 'Cari di catatan'),
      HgItem(Icons.tune, 'Pencarian lanjutan', 'Filter jenis/tanggal'),
      HgItem(Icons.calendar_month, 'Kalender', 'Catatan per tanggal'),
      HgItem(Icons.label, 'Kategori', 'Filter per kategori'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Keamanan & sinkron', [
      HgItem(Icons.lock, 'Kunci catatan', 'Lindungi dengan PIN'),
      HgItem(Icons.visibility_off, 'Mode privasi', 'Sembunyikan isi'),
      HgItem(Icons.backup_outlined, 'Cadangan', 'Simpan dan pulihkan'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Sinkron terenkripsi'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Pengingat & alarm', [
      HgItem(Icons.notifications_active, 'Jenis pengingat', 'Umum, obat, janji temu, acara'),
      HgItem(Icons.timer, 'Ingatkan sebelumnya', '5 mnt / 15 mnt / jam / hari'),
      HgItem(Icons.place, 'Lokasi janji temu', 'Tautan Google Maps atau pilih'),
      HgItem(Icons.attach_file, 'Undangan', 'Lampirkan gambar atau PDF'),
      HgItem(Icons.library_music, 'Pustaka suara', 'Nada + nada perangkat'),
      HgItem(Icons.alarm_on, 'Alarm andal', 'Jalan saat tertutup/restart, layar penuh, naikkan volume'),
      HgItem(Icons.history, 'Log pusat notifikasi', 'Setiap pengingat yang berbunyi dicatat otomatis — bisa dihapus'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Peningkatan terbaru', [
      HgItem(Icons.brush, 'Gambar lanjutan', 'Warna & tebal per goresan, kuas, penghapus'),
      HgItem(Icons.tune, 'Setelan pengingat', 'Nada, tunda, volume, pra-peringatan'),
      HgItem(Icons.lock, 'Terenkripsi & aman', 'Data terenkripsi di perangkat + cadangan otomatis'),
      HgItem(Icons.cloud_done, 'Sinkron aman', 'Terautentikasi & tangguh (tidak menghapus data)'),
      HgItem(Icons.system_update, 'Pembaruan dalam aplikasi', 'Periksa & pasang versi baru dari Pengaturan'),
      HgItem(Icons.restart_alt, 'Pengingat kedaluwarsa', 'Pengingat sekali yang lewat memudar — aktifkan untuk jadwal ulang'),
      HgItem(Icons.medication, 'Kursus obat', 'Tetapkan total dosis; sisa berkurang seiring waktu; dosis lalu & mendatang'),
      HgItem(Icons.checklist_rtl, 'Pilih banyak', 'Tekan lama → Pilih: aksi massal'),
      HgItem(Icons.bar_chart, 'Statistik catatan', 'Kata, karakter, baris & waktu baca'),
      HgItem(Icons.label_important_outline, 'Jumlah kategori', 'Chip menampilkan jumlah catatan'),
      HgItem(Icons.alarm, 'Lencana pengingat', 'Kartu menampilkan ikon alarm bila ada pengingat'),
      HgItem(Icons.density_small, 'Tampilan ringkas', 'Kartu lebih kecil — di Pengaturan'),
      HgItem(Icons.verified_outlined, 'Cadangan terverifikasi', 'Integritas dicek saat dibuat'),
      HgItem(Icons.restore_page_outlined, 'Pemulihan aman', 'Snapshot otomatis + batalkan pemulihan'),
      HgItem(Icons.swipe, 'Geser', 'Kanan arsip, kiri hapus (tampilan daftar)'),
      HgItem(Icons.search, 'Sorot pencarian', 'Kecocokan disorot • tanggal ramah'),
      HgItem(Icons.sell_outlined, 'Tag di kartu', 'Chip tag berwarna di tiap catatan'),
      HgItem(Icons.image_outlined, 'Bagikan sebagai gambar', 'Bagikan catatan sebagai gambar bergaya'),
      HgItem(Icons.data_object, 'Ekspor/impor JSON', 'Cadangan catatan yang terbaca & portabel'),
      HgItem(Icons.repeat, 'Pengulangan kustom', 'Ulangi pengingat tiap N hari'),
      HgItem(Icons.fact_check_outlined, 'Progres checklist', 'Bar menampilkan selesai/total'),
      HgItem(Icons.label_outline, 'Tag berwarna', 'Pilih warna tiap tag (tekan lama) di halaman Tag'),
      HgItem(Icons.dashboard_outlined, 'Navigasi tertata', 'Header: aksi cepat • ⋮: layanan cepat • ☰: pengaturan & pengelolaan'),
      HgItem(Icons.palette_outlined, 'Warna sistem', 'Tema dari wallpaper (Android 12+) — di Pengaturan'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Lainnya', [
      HgItem(Icons.format_textdirection_r_to_l, 'Arah per baris', 'Arab kanan, Inggris kiri'),
      HgItem(Icons.archive_outlined, 'Arsip & sampah', 'Pulihkan catatan'),
      HgItem(Icons.settings_outlined, 'Pengaturan', 'Halaman & bahasa default'),
    ]),
  ],
  'it': [
    HgSection(Icons.add_circle, _c1, true, 'Crea una nota (+)', [
      HgItem(Icons.edit_note, 'Nota', 'Testo semplice, direzione per riga'),
      HgItem(Icons.checklist, 'Lista attività', 'Righe con caselle'),
      HgItem(Icons.mic, 'Nota vocale', 'Registra audio'),
      HgItem(Icons.image, 'Immagine', 'Allega una foto'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Formattazione', [
      HgItem(Icons.format_bold, 'Grassetto · Corsivo · Sottolineato', 'Sul testo selezionato'),
      HgItem(Icons.format_color_text, 'Colori', 'Colore testo e sfondo'),
      HgItem(Icons.title, 'Titoli ed elenchi', 'Titoli, punti, numeri'),
      HgItem(Icons.format_align_right, 'Allineamento', 'Destra / centro / sinistra'),
      HgItem(Icons.format_line_spacing, 'Interlinea', 'Righe selezionate (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Dettatura vocale', 'Parla e scrive'),
      HgItem(Icons.picture_as_pdf, 'Esporta PDF', 'Salva la nota in PDF'),
      HgItem(Icons.description, 'Esporta Word', 'Salva un file .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Strumenti editor', [
      HgItem(Icons.push_pin, 'Fissa', 'Fissa in alto'),
      HgItem(Icons.palette_outlined, 'Colore e pagina', 'Sfondo, stile, righe'),
      HgItem(Icons.star, 'Preferito', 'Segna come preferito'),
      HgItem(Icons.alarm, 'Promemoria', 'Singolo o ripetuto'),
      HgItem(Icons.label_outline, 'Tag', 'Aggiungi tag'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Home e navigazione', [
      HgItem(Icons.search, 'Cerca', 'Cerca nelle note'),
      HgItem(Icons.tune, 'Ricerca avanzata', 'Filtra per tipo/data'),
      HgItem(Icons.calendar_month, 'Calendario', 'Note per data'),
      HgItem(Icons.label, 'Categorie', 'Filtra per categoria'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Sicurezza e sync', [
      HgItem(Icons.lock, 'Blocca nota', 'Proteggi con PIN'),
      HgItem(Icons.visibility_off, 'Modalità privata', 'Nascondi contenuti'),
      HgItem(Icons.backup_outlined, 'Backup', 'Salva e ripristina'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Sync crittografata'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Promemoria e sveglia', [
      HgItem(Icons.notifications_active, 'Tipi di promemoria', 'Generale, farmaco, appuntamento, evento'),
      HgItem(Icons.timer, 'Avvisa prima', '5 min / 15 min / ora / giorno'),
      HgItem(Icons.place, 'Luogo appuntamento', 'Link Google Maps o scegli'),
      HgItem(Icons.attach_file, 'Invito', 'Allega immagine o PDF'),
      HgItem(Icons.library_music, 'Libreria suoni', 'Suoni + suoni del dispositivo'),
      HgItem(Icons.alarm_on, 'Sveglia affidabile', 'Funziona chiusa/riavviata, schermo intero, alza volume'),
      HgItem(Icons.history, 'Registro del centro notifiche', 'Ogni promemoria attivato registrato in automatico — eliminabile'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Miglioramenti recenti', [
      HgItem(Icons.brush, 'Disegno avanzato', 'Colore e spessore per tratto, pennello, gomma'),
      HgItem(Icons.tune, 'Impostazioni promemoria', 'Suono, posticipa, volume, pre-avviso'),
      HgItem(Icons.lock, 'Cifrato e sicuro', 'Dati cifrati sul dispositivo + backup automatico'),
      HgItem(Icons.cloud_done, 'Sync sicura', 'Autenticata e robusta (non cancella mai i dati)'),
      HgItem(Icons.system_update, 'Aggiornamento in-app', 'Cerca e installa nuove versioni dalle Impostazioni'),
      HgItem(Icons.restart_alt, 'Promemoria scaduti', 'Quelli una tantum passati sbiadiscono — riattiva per riprogrammare'),
      HgItem(Icons.medication, 'Cicli di farmaci', 'Imposta dosi totali; il resto cala nel tempo; dosi passate e future'),
      HgItem(Icons.checklist_rtl, 'Selezione multipla', 'Pressione lunga → Seleziona: azioni in blocco'),
      HgItem(Icons.bar_chart, 'Statistiche nota', 'Parole, caratteri, righe e tempo di lettura'),
      HgItem(Icons.label_important_outline, 'Conteggi categorie', 'I chip mostrano quante note'),
      HgItem(Icons.alarm, 'Indicatore promemoria', 'Le schede mostrano un’icona sveglia'),
      HgItem(Icons.density_small, 'Vista compatta', 'Schede più piccole — nelle Impostazioni'),
      HgItem(Icons.verified_outlined, 'Backup verificati', 'Integrità controllata alla creazione'),
      HgItem(Icons.restore_page_outlined, 'Ripristino sicuro', 'Snapshot automatico + annulla ripristino'),
      HgItem(Icons.swipe, 'Scorri', 'Destra archivia, sinistra elimina (vista elenco)'),
      HgItem(Icons.search, 'Evidenzia ricerca', 'Corrispondenze evidenziate • date amichevoli'),
      HgItem(Icons.sell_outlined, 'Tag sulle schede', 'Chip tag colorati su ogni nota'),
      HgItem(Icons.image_outlined, 'Condividi come immagine', 'Condividi una nota come immagine'),
      HgItem(Icons.data_object, 'Esporta/importa JSON', 'Backup leggibile e portatile delle note'),
      HgItem(Icons.repeat, 'Ripetizione personalizzata', 'Ripeti un promemoria ogni N giorni'),
      HgItem(Icons.fact_check_outlined, 'Avanzamento checklist', 'Barra: completate/totale'),
      HgItem(Icons.label_outline, 'Tag colorati', 'Scegli un colore per tag (pressione lunga) nella pagina Tag'),
      HgItem(Icons.dashboard_outlined, 'Navigazione ordinata', 'Intestazione: azioni rapide • ⋮: servizi rapidi • ☰: impostazioni e gestione'),
      HgItem(Icons.palette_outlined, 'Colori di sistema', 'Tema dallo sfondo (Android 12+) — nelle Impostazioni'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Altro', [
      HgItem(Icons.format_textdirection_r_to_l, 'Direzione per riga', 'Arabo a destra, inglese a sinistra'),
      HgItem(Icons.archive_outlined, 'Archivio e cestino', 'Ripristina le note'),
      HgItem(Icons.settings_outlined, 'Impostazioni', 'Pagina e lingua predefinite'),
    ]),
  ],
  'ms': [
    HgSection(Icons.add_circle, _c1, true, 'Buat nota (+)', [
      HgItem(Icons.edit_note, 'Nota', 'Teks biasa, arah setiap baris'),
      HgItem(Icons.checklist, 'Senarai tugas', 'Baris dengan kotak semak'),
      HgItem(Icons.mic, 'Nota suara', 'Rakam audio'),
      HgItem(Icons.image, 'Imej', 'Lampirkan foto'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Pemformatan', [
      HgItem(Icons.format_bold, 'Tebal · Condong · Garis bawah', 'Pada teks dipilih'),
      HgItem(Icons.format_color_text, 'Warna', 'Warna teks dan sorotan'),
      HgItem(Icons.title, 'Tajuk & senarai', 'Tajuk, bulet, nombor'),
      HgItem(Icons.format_align_right, 'Penjajaran', 'Kanan / tengah / kiri'),
      HgItem(Icons.format_line_spacing, 'Jarak baris', 'Baris dipilih (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Taip suara', 'Cakap, ia menulis'),
      HgItem(Icons.picture_as_pdf, 'Eksport PDF', 'Simpan sebagai PDF'),
      HgItem(Icons.description, 'Eksport Word', 'Simpan fail .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Alat editor', [
      HgItem(Icons.push_pin, 'Sematkan', 'Sematkan ke atas'),
      HgItem(Icons.palette_outlined, 'Warna & halaman', 'Latar, gaya, garis'),
      HgItem(Icons.star, 'Kegemaran', 'Tanda kegemaran'),
      HgItem(Icons.alarm, 'Peringatan', 'Sekali atau berulang'),
      HgItem(Icons.label_outline, 'Tag', 'Tambah tag'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Utama & navigasi', [
      HgItem(Icons.search, 'Cari', 'Cari dalam nota'),
      HgItem(Icons.tune, 'Carian lanjutan', 'Tapis jenis/tarikh'),
      HgItem(Icons.calendar_month, 'Kalendar', 'Nota mengikut tarikh'),
      HgItem(Icons.label, 'Kategori', 'Tapis mengikut kategori'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Keselamatan & segerak', [
      HgItem(Icons.lock, 'Kunci nota', 'Lindungi dengan PIN'),
      HgItem(Icons.visibility_off, 'Mod privasi', 'Sembunyi kandungan'),
      HgItem(Icons.backup_outlined, 'Sandaran', 'Simpan dan pulih'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Segerak tersulit'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Peringatan & penggera', [
      HgItem(Icons.notifications_active, 'Jenis peringatan', 'Umum, ubat, temu janji, majlis'),
      HgItem(Icons.timer, 'Ingatkan sebelum', '5 min / 15 min / jam / hari'),
      HgItem(Icons.place, 'Lokasi temu janji', 'Pautan Google Maps atau pilih'),
      HgItem(Icons.attach_file, 'Jemputan', 'Lampirkan imej atau PDF'),
      HgItem(Icons.library_music, 'Pustaka bunyi', 'Nada + nada peranti'),
      HgItem(Icons.alarm_on, 'Penggera boleh harap', 'Berfungsi ditutup/dimulakan semula, skrin penuh, naik kuat'),
      HgItem(Icons.history, 'Log pusat pemberitahuan', 'Setiap peringatan berbunyi direkod automatik — boleh padam'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Penambahbaikan terkini', [
      HgItem(Icons.brush, 'Lukisan lanjutan', 'Warna & ketebalan setiap lakaran, berus, pemadam'),
      HgItem(Icons.tune, 'Tetapan peringatan', 'Nada, tunda, kelantangan, pra-amaran'),
      HgItem(Icons.lock, 'Tersulit & selamat', 'Data tersulit dalam peranti + sandaran auto'),
      HgItem(Icons.cloud_done, 'Segerak selamat', 'Disahkan & teguh (tidak memadam data)'),
      HgItem(Icons.system_update, 'Kemas kini dalam apl', 'Semak & pasang versi baharu dari Tetapan'),
      HgItem(Icons.restart_alt, 'Peringatan tamat', 'Yang sekali & lepas pudar — aktifkan semula untuk jadual semula'),
      HgItem(Icons.medication, 'Kursus ubat', 'Tetapkan jumlah dos; baki berkurang ikut masa; dos lepas & akan datang'),
      HgItem(Icons.checklist_rtl, 'Pilih berbilang', 'Tekan lama → Pilih: tindakan pukal'),
      HgItem(Icons.bar_chart, 'Statistik nota', 'Perkataan, aksara, baris & masa baca'),
      HgItem(Icons.label_important_outline, 'Kiraan kategori', 'Cip tunjuk bilangan nota'),
      HgItem(Icons.alarm, 'Lencana peringatan', 'Kad tunjuk ikon penggera bila ada peringatan'),
      HgItem(Icons.density_small, 'Paparan padat', 'Kad lebih kecil — dalam Tetapan'),
      HgItem(Icons.verified_outlined, 'Sandaran disahkan', 'Integriti disemak sebaik dibuat'),
      HgItem(Icons.restore_page_outlined, 'Pemulihan selamat', 'Snapshot auto + buat asal pemulihan'),
      HgItem(Icons.swipe, 'Leret', 'Kanan arkib, kiri padam (paparan senarai)'),
      HgItem(Icons.search, 'Serlah carian', 'Padanan diserlah • tarikh mesra'),
      HgItem(Icons.sell_outlined, 'Tag pada kad', 'Cip tag berwarna pada setiap nota'),
      HgItem(Icons.image_outlined, 'Kongsi sebagai imej', 'Kongsi nota sebagai imej bergaya'),
      HgItem(Icons.data_object, 'Eksport/import JSON', 'Sandaran nota boleh baca & mudah alih'),
      HgItem(Icons.repeat, 'Ulangan tersuai', 'Ulang peringatan setiap N hari'),
      HgItem(Icons.fact_check_outlined, 'Kemajuan checklist', 'Bar tunjuk selesai/jumlah'),
      HgItem(Icons.label_outline, 'Tag berwarna', 'Pilih warna setiap tag (tekan lama) di halaman Tag'),
      HgItem(Icons.dashboard_outlined, 'Navigasi tersusun', 'Pengepala: tindakan pantas • ⋮: perkhidmatan pantas • ☰: tetapan & pengurusan'),
      HgItem(Icons.palette_outlined, 'Warna sistem', 'Tema dari kertas dinding (Android 12+) — dalam Tetapan'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Lagi', [
      HgItem(Icons.format_textdirection_r_to_l, 'Arah setiap baris', 'Arab kanan, Inggeris kiri'),
      HgItem(Icons.archive_outlined, 'Arkib & sampah', 'Pulihkan nota anda'),
      HgItem(Icons.settings_outlined, 'Tetapan', 'Halaman & bahasa lalai'),
    ]),
  ],
  'hi': [
    HgSection(Icons.add_circle, _c1, true, 'नोट बनाएँ (+)', [
      HgItem(Icons.edit_note, 'नोट', 'सादा टेक्स्ट, हर लाइन की दिशा'),
      HgItem(Icons.checklist, 'चेकलिस्ट', 'चेकबॉक्स वाली लाइनें'),
      HgItem(Icons.mic, 'वॉइस नोट', 'ऑडियो रिकॉर्ड करें'),
      HgItem(Icons.image, 'इमेज', 'फ़ोटो जोड़ें'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'फ़ॉर्मेटिंग', [
      HgItem(Icons.format_bold, 'बोल्ड · इटैलिक · रेखांकित', 'चयनित टेक्स्ट पर'),
      HgItem(Icons.format_color_text, 'रंग', 'टेक्स्ट और हाइलाइट रंग'),
      HgItem(Icons.title, 'शीर्षक और सूचियाँ', 'शीर्षक, बुलेट, नंबर'),
      HgItem(Icons.format_align_right, 'संरेखण', 'दाएँ / केंद्र / बाएँ'),
      HgItem(Icons.format_line_spacing, 'लाइन स्पेसिंग', 'चयनित लाइनें (1.0–2.0)'),
      HgItem(Icons.mic_none, 'वॉइस टाइपिंग', 'बोलें, यह लिखता है'),
      HgItem(Icons.picture_as_pdf, 'PDF निर्यात', 'नोट को PDF सहेजें'),
      HgItem(Icons.description, 'Word निर्यात', '.doc फ़ाइल सहेजें'),
    ]),
    HgSection(Icons.tune, _c3, false, 'एडिटर टूल', [
      HgItem(Icons.push_pin, 'पिन', 'ऊपर पिन करें'),
      HgItem(Icons.palette_outlined, 'रंग और पेज', 'पृष्ठभूमि, शैली, रेखाएँ'),
      HgItem(Icons.star, 'पसंदीदा', 'पसंदीदा चिह्नित करें'),
      HgItem(Icons.alarm, 'रिमाइंडर', 'एक बार या दोहराव'),
      HgItem(Icons.label_outline, 'टैग', 'टैग जोड़ें'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'होम और नेविगेशन', [
      HgItem(Icons.search, 'खोज', 'अपने नोट्स में खोजें'),
      HgItem(Icons.tune, 'उन्नत खोज', 'प्रकार/तारीख से फ़िल्टर'),
      HgItem(Icons.calendar_month, 'कैलेंडर', 'तारीख अनुसार नोट'),
      HgItem(Icons.label, 'श्रेणियाँ', 'श्रेणी से फ़िल्टर'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'सुरक्षा और सिंक', [
      HgItem(Icons.lock, 'नोट लॉक', 'PIN से सुरक्षा'),
      HgItem(Icons.visibility_off, 'प्राइवेसी मोड', 'सामग्री छिपाएँ'),
      HgItem(Icons.backup_outlined, 'बैकअप', 'सहेजें और पुनर्स्थापित'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'एन्क्रिप्टेड सिंक'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'रिमाइंडर और अलार्म', [
      HgItem(Icons.notifications_active, 'रिमाइंडर के प्रकार', 'सामान्य, दवा, अपॉइंटमेंट, अवसर'),
      HgItem(Icons.timer, 'समय से पहले सूचना', '5 मि / 15 मि / घंटा / दिन'),
      HgItem(Icons.place, 'अपॉइंटमेंट स्थान', 'Google Maps लिंक या चुनें'),
      HgItem(Icons.attach_file, 'निमंत्रण', 'इमेज या PDF जोड़ें'),
      HgItem(Icons.library_music, 'ध्वनि लाइब्रेरी', 'टोन + डिवाइस टोन'),
      HgItem(Icons.alarm_on, 'भरोसेमंद अलार्म', 'बंद/रीस्टार्ट पर भी, फुल-स्क्रीन, आवाज़ बढ़ाता है'),
      HgItem(Icons.history, 'नोटिफिकेशन सेंटर लॉग', 'हर चला रिमाइंडर अपने आप दर्ज — हटाने की सुविधा'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'हाल के सुधार', [
      HgItem(Icons.brush, 'उन्नत ड्रॉइंग', 'हर स्ट्रोक का रंग व मोटाई, ब्रश, इरेज़र'),
      HgItem(Icons.tune, 'रिमाइंडर डिफ़ॉल्ट', 'टोन, स्नूज़, आवाज़, पूर्व-सूचना'),
      HgItem(Icons.lock, 'एन्क्रिप्टेड व सुरक्षित', 'डिवाइस पर एन्क्रिप्टेड डेटा + ऑटो बैकअप'),
      HgItem(Icons.cloud_done, 'सुरक्षित सिंक', 'प्रमाणित व मज़बूत (डेटा नहीं मिटाता)'),
      HgItem(Icons.system_update, 'इन-ऐप अपडेट', 'सेटिंग्स से नई वर्शन जांचें व इंस्टॉल करें — बिना मैनुअल डाउनलोड'),
      HgItem(Icons.restart_alt, 'समाप्त रिमाइंडर', 'बीते एक-बार रिमाइंडर फीके — पुनर्निर्धारित करने हेतु सक्रिय करें'),
      HgItem(Icons.medication, 'दवा कोर्स', 'कुल खुराक सेट करें; शेष समय से घटे; पिछली व आगामी खुराक'),
      HgItem(Icons.checklist_rtl, 'मल्टी-सिलेक्ट', 'देर तक दबाएँ → चुनें: बल्क क्रियाएँ'),
      HgItem(Icons.bar_chart, 'नोट आँकड़े', 'शब्द, अक्षर, पंक्तियाँ और पढ़ने का समय'),
      HgItem(Icons.label_important_outline, 'श्रेणी गणना', 'चिप दिखाते हैं कितने नोट'),
      HgItem(Icons.alarm, 'रिमाइंडर बैज', 'रिमाइंडर होने पर कार्ड पर अलार्म आइकन'),
      HgItem(Icons.density_small, 'संक्षिप्त दृश्य', 'छोटे कार्ड — सेटिंग्स में'),
      HgItem(Icons.verified_outlined, 'सत्यापित बैकअप', 'बनते ही अखंडता जाँची जाती है'),
      HgItem(Icons.restore_page_outlined, 'सुरक्षित पुनर्स्थापना', 'ऑटो स्नैपशॉट + पुनर्स्थापना पूर्ववत'),
      HgItem(Icons.swipe, 'स्वाइप', 'दाएँ आर्काइव, बाएँ हटाएँ (सूची दृश्य)'),
      HgItem(Icons.search, 'खोज हाइलाइट', 'मिलान हाइलाइट • सरल तिथियाँ'),
      HgItem(Icons.sell_outlined, 'कार्ड पर टैग', 'हर नोट पर रंगीन टैग चिप'),
      HgItem(Icons.image_outlined, 'छवि के रूप में साझा', 'नोट को सुंदर छवि के रूप में साझा करें'),
      HgItem(Icons.data_object, 'JSON निर्यात/आयात', 'आपके नोट्स का पठनीय, पोर्टेबल बैकअप'),
      HgItem(Icons.repeat, 'कस्टम दोहराव', 'किसी भी रिमाइंडर को हर N दिन दोहराएँ'),
      HgItem(Icons.fact_check_outlined, 'चेकलिस्ट प्रगति', 'बार दिखाता है पूर्ण/कुल'),
      HgItem(Icons.label_outline, 'रंगीन टैग', 'टैग पेज पर हर टैग का रंग चुनें (देर तक दबाएँ)'),
      HgItem(Icons.dashboard_outlined, 'व्यवस्थित नेविगेशन', 'हेडर: त्वरित क्रियाएँ • ⋮: त्वरित सेवाएँ • ☰: सेटिंग्स और प्रबंधन'),
      HgItem(Icons.palette_outlined, 'सिस्टम रंग', 'वॉलपेपर से थीम (Android 12+) — सेटिंग्स में'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'अधिक', [
      HgItem(Icons.format_textdirection_r_to_l, 'हर लाइन की दिशा', 'अरबी दाएँ, अंग्रेज़ी बाएँ'),
      HgItem(Icons.archive_outlined, 'आर्काइव और ट्रैश', 'नोट्स पुनर्स्थापित करें'),
      HgItem(Icons.settings_outlined, 'सेटिंग्स', 'डिफ़ॉल्ट पेज और भाषा'),
    ]),
  ],
  'bn': [
    HgSection(Icons.add_circle, _c1, true, 'নোট তৈরি (+)', [
      HgItem(Icons.edit_note, 'নোট', 'সাধারণ টেক্সট, প্রতি লাইনে দিক'),
      HgItem(Icons.checklist, 'চেকলিস্ট', 'চেকবক্স সহ লাইন'),
      HgItem(Icons.mic, 'ভয়েস নোট', 'অডিও রেকর্ড'),
      HgItem(Icons.image, 'ছবি', 'ছবি সংযুক্ত করুন'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'ফরম্যাটিং', [
      HgItem(Icons.format_bold, 'বোল্ড · ইটালিক · আন্ডারলাইন', 'নির্বাচিত টেক্সটে'),
      HgItem(Icons.format_color_text, 'রং', 'টেক্সট ও হাইলাইট রং'),
      HgItem(Icons.title, 'শিরোনাম ও তালিকা', 'শিরোনাম, বুলেট, সংখ্যা'),
      HgItem(Icons.format_align_right, 'প্রান্তিককরণ', 'ডান / মাঝ / বাম'),
      HgItem(Icons.format_line_spacing, 'লাইন স্পেসিং', 'নির্বাচিত লাইন (1.0–2.0)'),
      HgItem(Icons.mic_none, 'ভয়েস টাইপিং', 'বলুন, এটি লেখে'),
      HgItem(Icons.picture_as_pdf, 'PDF এক্সপোর্ট', 'নোট PDF সংরক্ষণ'),
      HgItem(Icons.description, 'Word এক্সপোর্ট', '.doc ফাইল সংরক্ষণ'),
    ]),
    HgSection(Icons.tune, _c3, false, 'এডিটর সরঞ্জাম', [
      HgItem(Icons.push_pin, 'পিন', 'উপরে পিন করুন'),
      HgItem(Icons.palette_outlined, 'রং ও পৃষ্ঠা', 'পটভূমি, স্টাইল, রেখা'),
      HgItem(Icons.star, 'প্রিয়', 'প্রিয় চিহ্নিত করুন'),
      HgItem(Icons.alarm, 'রিমাইন্ডার', 'একবার বা পুনরাবৃত্ত'),
      HgItem(Icons.label_outline, 'ট্যাগ', 'ট্যাগ যোগ করুন'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'হোম ও নেভিগেশন', [
      HgItem(Icons.search, 'অনুসন্ধান', 'নোটে খুঁজুন'),
      HgItem(Icons.tune, 'উন্নত অনুসন্ধান', 'ধরন/তারিখে ফিল্টার'),
      HgItem(Icons.calendar_month, 'ক্যালেন্ডার', 'তারিখ অনুযায়ী নোট'),
      HgItem(Icons.label, 'বিভাগ', 'বিভাগ অনুযায়ী ফিল্টার'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'নিরাপত্তা ও সিঙ্ক', [
      HgItem(Icons.lock, 'নোট লক', 'PIN দিয়ে সুরক্ষা'),
      HgItem(Icons.visibility_off, 'প্রাইভেসি মোড', 'বিষয়বস্তু লুকান'),
      HgItem(Icons.backup_outlined, 'ব্যাকআপ', 'সংরক্ষণ ও পুনরুদ্ধার'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'এনক্রিপ্টেড সিঙ্ক'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'রিমাইন্ডার ও অ্যালার্ম', [
      HgItem(Icons.notifications_active, 'রিমাইন্ডারের ধরন', 'সাধারণ, ওষুধ, অ্যাপয়েন্টমেন্ট, অনুষ্ঠান'),
      HgItem(Icons.timer, 'সময়ের আগে সতর্কতা', '5 মি / 15 মি / ঘণ্টা / দিন'),
      HgItem(Icons.place, 'অ্যাপয়েন্টমেন্ট স্থান', 'Google Maps লিঙ্ক বা নির্বাচন'),
      HgItem(Icons.attach_file, 'আমন্ত্রণ', 'ছবি বা PDF সংযুক্ত করুন'),
      HgItem(Icons.library_music, 'সাউন্ড লাইব্রেরি', 'টোন + ডিভাইস টোন'),
      HgItem(Icons.alarm_on, 'নির্ভরযোগ্য অ্যালার্ম', 'বন্ধ/রিস্টার্টেও চলে, ফুল-স্ক্রিন, ভলিউম বাড়ায়'),
      HgItem(Icons.history, 'নোটিফিকেশন সেন্টার লগ', 'প্রতিটি বাজা রিমাইন্ডার স্বয়ংক্রিয় রেকর্ড — মুছে ফেলা যায়'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'সাম্প্রতিক উন্নতি', [
      HgItem(Icons.brush, 'উন্নত অঙ্কন', 'প্রতি স্ট্রোকে রং ও পুরুত্ব, ব্রাশ, ইরেজার'),
      HgItem(Icons.tune, 'রিমাইন্ডার ডিফল্ট', 'টোন, স্নুজ, ভলিউম, প্রি-অ্যালার্ট'),
      HgItem(Icons.lock, 'এনক্রিপ্টেড ও নিরাপদ', 'ডিভাইসে এনক্রিপ্টেড ডেটা + অটো ব্যাকআপ'),
      HgItem(Icons.cloud_done, 'নিরাপদ সিঙ্ক', 'প্রমাণিত ও দৃঢ় (ডেটা মোছে না)'),
      HgItem(Icons.system_update, 'ইন-অ্যাপ আপডেট', 'সেটিংস থেকে নতুন সংস্করণ দেখুন ও ইনস্টল করুন'),
      HgItem(Icons.restart_alt, 'মেয়াদোত্তীর্ণ রিমাইন্ডার', 'অতীত একবারের রিমাইন্ডার ম্লান — পুনঃনির্ধারণে সক্রিয় করুন'),
      HgItem(Icons.medication, 'ওষুধ কোর্স', 'মোট ডোজ নির্ধারণ; বাকি সময়ের সাথে কমে; অতীত ও আসন্ন ডোজ'),
      HgItem(Icons.checklist_rtl, 'মাল্টি-সিলেক্ট', 'চেপে ধরুন → নির্বাচন: বাল্ক অ্যাকশন'),
      HgItem(Icons.bar_chart, 'নোট পরিসংখ্যান', 'শব্দ, অক্ষর, লাইন ও পড়ার সময়'),
      HgItem(Icons.label_important_outline, 'বিভাগ গণনা', 'চিপে কতটি নোট দেখায়'),
      HgItem(Icons.alarm, 'রিমাইন্ডার ব্যাজ', 'রিমাইন্ডার থাকলে কার্ডে অ্যালার্ম আইকন'),
      HgItem(Icons.density_small, 'সংক্ষিপ্ত ভিউ', 'ছোট কার্ড — সেটিংসে'),
      HgItem(Icons.verified_outlined, 'যাচাইকৃত ব্যাকআপ', 'তৈরির মুহূর্তেই অখণ্ডতা পরীক্ষা'),
      HgItem(Icons.restore_page_outlined, 'নিরাপদ পুনরুদ্ধার', 'অটো স্ন্যাপশট + পুনরুদ্ধার পূর্বাবস্থায়'),
      HgItem(Icons.swipe, 'সোয়াইপ', 'ডানে আর্কাইভ, বাঁয়ে মুছুন (তালিকা ভিউ)'),
      HgItem(Icons.search, 'সার্চ হাইলাইট', 'মিল হাইলাইট • সহজ তারিখ'),
      HgItem(Icons.sell_outlined, 'কার্ডে ট্যাগ', 'প্রতিটি নোটে রঙিন ট্যাগ চিপ'),
      HgItem(Icons.image_outlined, 'ছবি হিসেবে শেয়ার', 'নোট সুন্দর ছবি হিসেবে শেয়ার করুন'),
      HgItem(Icons.data_object, 'JSON রপ্তানি/আমদানি', 'নোটের পঠনযোগ্য, বহনযোগ্য ব্যাকআপ'),
      HgItem(Icons.repeat, 'কাস্টম পুনরাবৃত্তি', 'যেকোনো রিমাইন্ডার প্রতি N দিনে'),
      HgItem(Icons.fact_check_outlined, 'চেকলিস্ট অগ্রগতি', 'বার দেখায় সম্পন্ন/মোট'),
      HgItem(Icons.label_outline, 'রঙিন ট্যাগ', 'ট্যাগ পেজে প্রতিটি ট্যাগের রং বেছে নিন (চেপে ধরে)'),
      HgItem(Icons.dashboard_outlined, 'সাজানো নেভিগেশন', 'হেডার: দ্রুত অ্যাকশন • ⋮: দ্রুত সেবা • ☰: সেটিংস ও ব্যবস্থাপনা'),
      HgItem(Icons.palette_outlined, 'সিস্টেম রং', 'ওয়ালপেপার থেকে থিম (Android 12+) — সেটিংসে'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'আরও', [
      HgItem(Icons.format_textdirection_r_to_l, 'প্রতি লাইনে দিক', 'আরবি ডানে, ইংরেজি বামে'),
      HgItem(Icons.archive_outlined, 'আর্কাইভ ও ট্র্যাশ', 'নোট পুনরুদ্ধার'),
      HgItem(Icons.settings_outlined, 'সেটিংস', 'ডিফল্ট পৃষ্ঠা ও ভাষা'),
    ]),
  ],
  'fa': [
    HgSection(Icons.add_circle, _c1, true, 'ساخت یادداشت (+)', [
      HgItem(Icons.edit_note, 'یادداشت', 'متن ساده، جهت هر خط'),
      HgItem(Icons.checklist, 'فهرست کارها', 'خطوط با کادر تیک'),
      HgItem(Icons.mic, 'یادداشت صوتی', 'ضبط صدا'),
      HgItem(Icons.image, 'تصویر', 'پیوست عکس'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'قالب‌بندی', [
      HgItem(Icons.format_bold, 'پررنگ · کج · زیرخط', 'روی متن انتخاب‌شده'),
      HgItem(Icons.format_color_text, 'رنگ‌ها', 'رنگ متن و هایلایت'),
      HgItem(Icons.title, 'عنوان‌ها و فهرست‌ها', 'عنوان، گلوله، شماره'),
      HgItem(Icons.format_align_right, 'ترازبندی', 'راست / وسط / چپ'),
      HgItem(Icons.format_line_spacing, 'فاصله خطوط', 'خطوط انتخابی (1.0–2.0)'),
      HgItem(Icons.mic_none, 'تایپ صوتی', 'صحبت کن، می‌نویسد'),
      HgItem(Icons.picture_as_pdf, 'خروجی PDF', 'ذخیره یادداشت به PDF'),
      HgItem(Icons.description, 'خروجی Word', 'ذخیره فایل .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'ابزارهای ویرایشگر', [
      HgItem(Icons.push_pin, 'سنجاق', 'سنجاق به بالا'),
      HgItem(Icons.palette_outlined, 'رنگ و صفحه', 'پس‌زمینه، سبک، خطوط'),
      HgItem(Icons.star, 'علاقه‌مندی', 'علامت علاقه‌مندی'),
      HgItem(Icons.alarm, 'یادآور', 'یک‌بار یا تکرارشونده'),
      HgItem(Icons.label_outline, 'برچسب‌ها', 'افزودن برچسب'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'خانه و پیمایش', [
      HgItem(Icons.search, 'جستجو', 'جستجو در یادداشت‌ها'),
      HgItem(Icons.tune, 'جستجوی پیشرفته', 'فیلتر بر اساس نوع/تاریخ'),
      HgItem(Icons.calendar_month, 'تقویم', 'یادداشت بر اساس تاریخ'),
      HgItem(Icons.label, 'دسته‌ها', 'فیلتر بر اساس دسته'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'امنیت و همگام‌سازی', [
      HgItem(Icons.lock, 'قفل یادداشت', 'محافظت با PIN'),
      HgItem(Icons.visibility_off, 'حالت حریم خصوصی', 'پنهان کردن محتوا'),
      HgItem(Icons.backup_outlined, 'پشتیبان', 'ذخیره و بازیابی'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'همگام‌سازی رمزنگاری‌شده'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'یادآورها و زنگ', [
      HgItem(Icons.notifications_active, 'انواع یادآور', 'عمومی، دارو، قرار، مناسبت'),
      HgItem(Icons.timer, 'هشدار پیش از موعد', '۵د / ۱۵د / ساعت / روز'),
      HgItem(Icons.place, 'مکان قرار', 'لینک گوگل‌مپ یا انتخاب'),
      HgItem(Icons.attach_file, 'دعوت‌نامه', 'پیوست عکس یا PDF'),
      HgItem(Icons.library_music, 'کتابخانه صداها', 'آهنگ‌ها + آهنگ‌های دستگاه'),
      HgItem(Icons.alarm_on, 'زنگ مطمئن', 'حتی بسته/پس از ری‌استارت، تمام‌صفحه، صدا را بالا می‌برد'),
      HgItem(Icons.history, 'گزارش مرکز اعلان‌ها', 'هر یادآور اجراشده خودکار ثبت می‌شود — با حذف'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'بهبودهای اخیر', [
      HgItem(Icons.brush, 'طراحی پیشرفته', 'رنگ و ضخامت برای هر خط، قلم‌مو، پاک‌کن'),
      HgItem(Icons.tune, 'تنظیمات یادآور', 'آهنگ، تعویق، صدا، هشدار پیش از موعد'),
      HgItem(Icons.lock, 'رمزنگاری‌شده و امن', 'داده‌های رمزنگاری‌شده روی دستگاه + پشتیبان خودکار'),
      HgItem(Icons.cloud_done, 'همگام‌سازی امن', 'احرازشده و مقاوم (داده‌ها را حذف نمی‌کند)'),
      HgItem(Icons.system_update, 'به‌روزرسانی درون‌برنامه', 'نسخه‌های جدید را از تنظیمات بررسی و نصب کنید'),
      HgItem(Icons.restart_alt, 'یادآورهای منقضی', 'یک‌باره‌های گذشته کم‌رنگ می‌شوند — برای زمان‌بندی دوباره فعال کنید'),
      HgItem(Icons.medication, 'دوره‌های دارو', 'تعداد کل دوز را تعیین کنید؛ باقی‌مانده با زمان کم می‌شود؛ دوزهای گذشته و آینده'),
      HgItem(Icons.checklist_rtl, 'انتخاب چندتایی', 'نگه‌داشتن ← انتخاب: عملیات گروهی'),
      HgItem(Icons.bar_chart, 'آمار یادداشت', 'کلمات، نویسه‌ها، خطوط و زمان مطالعه'),
      HgItem(Icons.label_important_outline, 'شمار دسته‌ها', 'تراشه‌ها تعداد یادداشت‌ها را نشان می‌دهند'),
      HgItem(Icons.alarm, 'نشان یادآور', 'هنگام وجود یادآور، نماد زنگ روی کارت'),
      HgItem(Icons.density_small, 'نمای فشرده', 'کارت‌های کوچک‌تر — در تنظیمات'),
      HgItem(Icons.verified_outlined, 'نسخه‌های تأییدشده', 'سلامت در لحظهٔ ساخت بررسی می‌شود'),
      HgItem(Icons.restore_page_outlined, 'بازیابی امن', 'عکس امنیتی خودکار + واگرد بازیابی'),
      HgItem(Icons.swipe, 'کشیدن', 'راست بایگانی، چپ حذف (نمای فهرست)'),
      HgItem(Icons.search, 'هایلایت جستجو', 'تطبیق‌ها هایلایت • تاریخ‌های ساده'),
      HgItem(Icons.sell_outlined, 'برچسب روی کارت‌ها', 'تراشه‌های برچسب رنگی روی هر یادداشت'),
      HgItem(Icons.image_outlined, 'اشتراک به‌صورت تصویر', 'هر یادداشت را به‌صورت تصویر زیبا به اشتراک بگذارید'),
      HgItem(Icons.data_object, 'برون‌بری/درون‌ری JSON', 'نسخهٔ خوانا و قابل‌انتقال یادداشت‌ها'),
      HgItem(Icons.repeat, 'تکرار سفارشی', 'هر یادآور را هر N روز تکرار کنید'),
      HgItem(Icons.fact_check_outlined, 'پیشرفت چک‌لیست', 'نوار: انجام‌شده/کل'),
      HgItem(Icons.label_outline, 'برچسب‌های رنگی', 'برای هر برچسب رنگ انتخاب کنید (نگه‌داشتن) در صفحه برچسب‌ها'),
      HgItem(Icons.dashboard_outlined, 'ناوبری منظم', 'سربرگ: کارهای سریع • ⋮: خدمات سریع • ☰: تنظیمات و مدیریت'),
      HgItem(Icons.palette_outlined, 'رنگ‌های سیستم', 'تم از تصویر زمینه (اندروید ۱۲+) — در تنظیمات'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'بیشتر', [
      HgItem(Icons.format_textdirection_r_to_l, 'جهت هر خط', 'عربی راست، انگلیسی چپ'),
      HgItem(Icons.archive_outlined, 'بایگانی و زباله‌دان', 'بازیابی یادداشت‌ها'),
      HgItem(Icons.settings_outlined, 'تنظیمات', 'صفحه و زبان پیش‌فرض'),
    ]),
  ],
  'ru': [
    HgSection(Icons.add_circle, _c1, true, 'Создать заметку (+)', [
      HgItem(Icons.edit_note, 'Заметка', 'Простой текст, направление по строке'),
      HgItem(Icons.checklist, 'Список задач', 'Строки с флажками'),
      HgItem(Icons.mic, 'Голосовая заметка', 'Запись звука'),
      HgItem(Icons.image, 'Изображение', 'Прикрепить фото'),
    ]),
    HgSection(Icons.text_format, _c2, false, 'Форматирование', [
      HgItem(Icons.format_bold, 'Жирный · Курсив · Подчёркнутый', 'К выделенному тексту'),
      HgItem(Icons.format_color_text, 'Цвета', 'Цвет текста и фона'),
      HgItem(Icons.title, 'Заголовки и списки', 'Заголовки, маркеры, номера'),
      HgItem(Icons.format_align_right, 'Выравнивание', 'Право / центр / лево'),
      HgItem(Icons.format_line_spacing, 'Межстрочный интервал', 'Выбранные строки (1.0–2.0)'),
      HgItem(Icons.mic_none, 'Голосовой ввод', 'Говорите — пишется'),
      HgItem(Icons.picture_as_pdf, 'Экспорт в PDF', 'Сохранить как PDF'),
      HgItem(Icons.description, 'Экспорт в Word', 'Сохранить файл .doc'),
    ]),
    HgSection(Icons.tune, _c3, false, 'Инструменты редактора', [
      HgItem(Icons.push_pin, 'Закрепить', 'Закрепить вверху'),
      HgItem(Icons.palette_outlined, 'Цвет и страница', 'Фон, стиль, линии'),
      HgItem(Icons.star, 'Избранное', 'Отметить избранным'),
      HgItem(Icons.alarm, 'Напоминание', 'Разовое или повтор'),
      HgItem(Icons.label_outline, 'Теги', 'Добавить теги'),
    ]),
    HgSection(Icons.home_outlined, _c4, false, 'Главная и навигация', [
      HgItem(Icons.search, 'Поиск', 'Поиск в заметках'),
      HgItem(Icons.tune, 'Расширенный поиск', 'Фильтр по типу/дате'),
      HgItem(Icons.calendar_month, 'Календарь', 'Заметки по дате'),
      HgItem(Icons.label, 'Категории', 'Фильтр по категории'),
    ]),
    HgSection(Icons.shield_outlined, _c6, false, 'Безопасность и синхронизация', [
      HgItem(Icons.lock, 'Заблокировать', 'Защита PIN-кодом'),
      HgItem(Icons.visibility_off, 'Режим приватности', 'Скрыть содержимое'),
      HgItem(Icons.backup_outlined, 'Резервная копия', 'Сохранить и восстановить'),
      HgItem(Icons.cloud, 'Google Drive / WebDAV', 'Шифрованная синхронизация'),
    ]),
    HgSection(Icons.alarm, _c5, false, 'Напоминания и будильник', [
      HgItem(Icons.notifications_active, 'Типы напоминаний', 'Общее, лекарство, встреча, событие'),
      HgItem(Icons.timer, 'Предупредить заранее', '5 мин / 15 мин / час / день'),
      HgItem(Icons.place, 'Место встречи', 'Ссылка Google Maps или выбор'),
      HgItem(Icons.attach_file, 'Приглашение', 'Прикрепить изображение или PDF'),
      HgItem(Icons.library_music, 'Библиотека звуков', 'Сигналы + сигналы устройства'),
      HgItem(Icons.alarm_on, 'Надёжный будильник', 'Работает закрытым/после перезагрузки, на весь экран, повышает громкость'),
      HgItem(Icons.history, 'Журнал центра уведомлений', 'Каждое сработавшее напоминание записывается само — можно удалить'),
    ]),
    HgSection(Icons.auto_awesome, _c7, false, 'Последние улучшения', [
      HgItem(Icons.brush, 'Продвинутое рисование', 'Цвет и толщина для каждого штриха, кисть, ластик'),
      HgItem(Icons.tune, 'Настройки напоминаний', 'Сигнал, отложить, громкость, предупреждение'),
      HgItem(Icons.lock, 'Шифрование и защита', 'Данные зашифрованы на устройстве + авто-резерв'),
      HgItem(Icons.cloud_done, 'Безопасная синхронизация', 'С проверкой и устойчивая (не удаляет данные)'),
      HgItem(Icons.system_update, 'Обновление в приложении', 'Проверка и установка новых версий из настроек'),
      HgItem(Icons.restart_alt, 'Истёкшие напоминания', 'Прошедшие разовые тускнеют — активируйте для переноса'),
      HgItem(Icons.medication, 'Курсы лекарств', 'Задайте число доз; остаток убывает со временем; прошлые и будущие дозы'),
      HgItem(Icons.checklist_rtl, 'Множественный выбор', 'Долгое нажатие → Выбрать: массовые действия'),
      HgItem(Icons.bar_chart, 'Статистика заметки', 'Слова, символы, строки и время чтения'),
      HgItem(Icons.label_important_outline, 'Счётчики категорий', 'Чипы показывают число заметок'),
      HgItem(Icons.alarm, 'Значок напоминания', 'На карточке значок будильника при напоминании'),
      HgItem(Icons.density_small, 'Компактный вид', 'Меньше карточки — в настройках'),
      HgItem(Icons.verified_outlined, 'Проверенные копии', 'Целостность проверяется при создании'),
      HgItem(Icons.restore_page_outlined, 'Безопасное восстановление', 'Авто-снимок + отмена восстановления'),
      HgItem(Icons.swipe, 'Свайп', 'Вправо — архив, влево — удалить (список)'),
      HgItem(Icons.search, 'Подсветка поиска', 'Совпадения выделены • удобные даты'),
      HgItem(Icons.sell_outlined, 'Теги на карточках', 'Цветные теги на каждой заметке'),
      HgItem(Icons.image_outlined, 'Поделиться картинкой', 'Заметка как стильная картинка'),
      HgItem(Icons.data_object, 'Экспорт/импорт JSON', 'Читаемая переносимая копия заметок'),
      HgItem(Icons.repeat, 'Своё повторение', 'Повтор любого напоминания каждые N дней'),
      HgItem(Icons.fact_check_outlined, 'Прогресс чек-листа', 'Полоса: выполнено/всего'),
      HgItem(Icons.label_outline, 'Цветные теги', 'Выберите цвет тега (долгое нажатие) на странице тегов'),
      HgItem(Icons.dashboard_outlined, 'Упорядоченная навигация', 'Шапка: быстрые действия • ⋮: быстрые сервисы • ☰: настройки и управление'),
      HgItem(Icons.palette_outlined, 'Системные цвета', 'Тема из обоев (Android 12+) — в настройках'),
    ]),
    HgSection(Icons.handyman_outlined, _c8, false, 'Ещё', [
      HgItem(Icons.format_textdirection_r_to_l, 'Направление по строке', 'Арабский справа, английский слева'),
      HgItem(Icons.archive_outlined, 'Архив и корзина', 'Восстановить заметки'),
      HgItem(Icons.settings_outlined, 'Настройки', 'Страница и язык по умолчанию'),
    ]),
  ],
};

const Map<String, HgChrome> _hgChrome = {
  'en': HgChrome('Every tool — its shape and function', 'items', 'Updated: 2026-06-22'),
  'ar': HgChrome('كل أداة وشكلها ووظيفتها', 'عنصر', 'آخر تحديث: 2026-06-22'),
  'es': HgChrome('Cada herramienta: su forma y función', 'elementos', 'Actualizado: 2026-06-22'),
  'de': HgChrome('Jedes Werkzeug – Form und Funktion', 'Einträge', 'Aktualisiert: 2026-06-22'),
  'fil': HgChrome('Bawat tool — hugis at gamit', 'item', 'Na-update: 2026-06-22'),
  'fr': HgChrome('Chaque outil — sa forme et sa fonction', 'éléments', 'Mis à jour : 2026-06-22'),
  'id': HgChrome('Setiap alat — bentuk dan fungsinya', 'item', 'Diperbarui: 2026-06-22'),
  'it': HgChrome('Ogni strumento — forma e funzione', 'elementi', 'Aggiornato: 2026-06-22'),
  'ms': HgChrome('Setiap alat — bentuk dan fungsi', 'item', 'Dikemas kini: 2026-06-22'),
  'hi': HgChrome('हर टूल — उसका आकार और काम', 'आइटम', 'अपडेट: 2026-06-22'),
  'bn': HgChrome('প্রতিটি টুল — আকৃতি ও কাজ', 'আইটেম', 'আপডেট: 2026-06-22'),
  'fa': HgChrome('هر ابزار — شکل و کارکرد آن', 'مورد', 'به‌روزرسانی: 2026-06-22'),
  'ru': HgChrome('Каждый инструмент — форма и функция', 'элементов', 'Обновлено: 2026-06-22'),
};

List<HgSection> helpSections(String lang) => _hg[lang] ?? _hg['en']!;
HgChrome helpChrome(String lang) => _hgChrome[lang] ?? _hgChrome['en']!;
